# backend/app/utils/csv_parser.py

"""
CSV parser utility for round-trip testing.

This module provides functionality to parse CSV files generated by the
csv_generator utility and return structured data for validation.

Requirements: 28.1-28.3, 28.7
"""

import csv
from typing import Dict, List, Any, Optional
from pathlib import Path
from decimal import Decimal, InvalidOperation
from datetime import datetime

from app.logging_config import get_logger

logger = get_logger(__name__)


class CSVParseError(Exception):
    """Exception raised when CSV parsing fails"""
    pass


def parse_csv(file_path: str, encoding: str = 'utf-8') -> Dict[str, Any]:
    """
    Parse a CSV file and return structured data.
    
    This function reads a CSV file and extracts data, returning it in a
    structured format that matches the export format.
    
    Args:
        file_path: Path to the CSV file to parse
        encoding: File encoding (default: utf-8)
    
    Returns:
        Dictionary containing parsed data with headers and rows
    
    Raises:
        CSVParseError: If the file cannot be parsed or is invalid
        FileNotFoundError: If the file does not exist
    
    Example:
        >>> data = parse_csv('report.csv')
        >>> print(data['headers'])
        ['Product', 'Cost', 'Margin']
    """
    file_path_obj = Path(file_path)
    
    if not file_path_obj.exists():
        raise FileNotFoundError(f"CSV file not found: {file_path}")
    
    try:
        with open(file_path, 'r', encoding=encoding, newline='') as csvfile:
            # Detect dialect
            sample = csvfile.read(1024)
            csvfile.seek(0)
            
            try:
                dialect = csv.Sniffer().sniff(sample)
            except csv.Error:
                # Fall back to default dialect
                dialect = csv.excel
            
            reader = csv.DictReader(csvfile, dialect=dialect)
            
            headers = reader.fieldnames or []
            rows = []
            
            for row_idx, row in enumerate(reader, start=2):  # Start at 2 (1 is header)
                parsed_row = {}
                for header in headers:
                    value = row.get(header, '')
                    parsed_row[header] = _parse_csv_value(value)
                
                # Only add non-empty rows
                if any(v is not None and v != '' for v in parsed_row.values()):
                    rows.append(parsed_row)
        
        result = {
            'headers': list(headers),
            'rows': rows,
            'row_count': len(rows),
            'column_count': len(headers),
            'encoding': encoding
        }
        
        logger.info(
            "csv_parsed",
            file_path=file_path,
            row_count=len(rows),
            column_count=len(headers)
        )
        
        return result
        
    except Exception as e:
        logger.error(
            "csv_parse_failed",
            file_path=file_path,
            error=str(e)
        )
        raise CSVParseError(f"Failed to parse CSV file: {str(e)}") from e


def _parse_csv_value(value: str) -> Any:
    """
    Parse a CSV cell value and convert to appropriate Python type.
    
    Args:
        value: The string value from CSV
    
    Returns:
        Parsed value in appropriate Python type
    """
    if not value or value.strip() == '':
        return None
    
    value = value.strip()
    
    # Handle boolean values
    if value.lower() in ('true', 'yes', '1'):
        return True
    if value.lower() in ('false', 'no', '0'):
        return False
    
    # Handle None/null values
    if value.lower() in ('none', 'null', 'n/a', 'na'):
        return None
    
    # Try to parse as number
    # Check for currency symbols
    if value.startswith('$') or value.startswith('€') or value.startswith('£'):
        try:
            # Remove currency symbol and commas
            numeric_str = value[1:].replace(',', '')
            return float(numeric_str)
        except ValueError:
            pass
    
    # Check for percentage
    if value.endswith('%'):
        try:
            return float(value[:-1]) / 100
        except ValueError:
            pass
    
    # Try to parse as integer
    try:
        return int(value)
    except ValueError:
        pass
    
    # Try to parse as float
    try:
        # Remove commas for thousands separator
        numeric_str = value.replace(',', '')
        return float(numeric_str)
    except ValueError:
        pass
    
    # Try to parse as date/datetime
    for date_format in [
        '%Y-%m-%d',
        '%Y-%m-%dT%H:%M:%S',
        '%Y-%m-%d %H:%M:%S',
        '%m/%d/%Y',
        '%d/%m/%Y'
    ]:
        try:
            dt = datetime.strptime(value, date_format)
            return dt.isoformat()
        except ValueError:
            continue
    
    # Return as string if no other type matches
    return value


def validate_csv_data(data: Dict[str, Any], expected_structure: Optional[Dict[str, Any]] = None) -> bool:
    """
    Validate parsed CSV data against expected structure.
    
    Args:
        data: Parsed CSV data
        expected_structure: Optional expected structure to validate against
    
    Returns:
        True if validation passes
    
    Raises:
        ValueError: If validation fails
    """
    if 'headers' not in data:
        raise ValueError("Invalid CSV data: missing 'headers' key")
    
    if 'rows' not in data:
        raise ValueError("Invalid CSV data: missing 'rows' key")
    
    if not isinstance(data['headers'], list):
        raise ValueError("Invalid CSV data: 'headers' must be a list")
    
    if not isinstance(data['rows'], list):
        raise ValueError("Invalid CSV data: 'rows' must be a list")
    
    if expected_structure:
        # Validate headers if specified
        if 'headers' in expected_structure:
            expected_headers = expected_structure['headers']
            actual_headers = data['headers']
            
            if expected_headers != actual_headers:
                raise ValueError(
                    f"Header mismatch: expected {expected_headers}, got {actual_headers}"
                )
        
        # Validate minimum row count if specified
        if 'min_rows' in expected_structure:
            min_rows = expected_structure['min_rows']
            actual_rows = len(data['rows'])
            
            if actual_rows < min_rows:
                raise ValueError(
                    f"Insufficient rows: expected at least {min_rows}, got {actual_rows}"
                )
        
        # Validate data types if specified
        if 'column_types' in expected_structure:
            column_types = expected_structure['column_types']
            
            for row_idx, row in enumerate(data['rows']):
                for column, expected_type in column_types.items():
                    if column in row and row[column] is not None:
                        actual_value = row[column]
                        
                        if expected_type == 'number' and not isinstance(actual_value, (int, float)):
                            raise ValueError(
                                f"Type mismatch in row {row_idx + 1}, column '{column}': "
                                f"expected number, got {type(actual_value).__name__}"
                            )
                        
                        if expected_type == 'string' and not isinstance(actual_value, str):
                            raise ValueError(
                                f"Type mismatch in row {row_idx + 1}, column '{column}': "
                                f"expected string, got {type(actual_value).__name__}"
                            )
    
    logger.info(
        "csv_validation_passed",
        row_count=len(data['rows']),
        column_count=len(data['headers'])
    )
    
    return True


def compare_csv_data(original: Dict[str, Any], parsed: Dict[str, Any], tolerance: float = 0.01) -> bool:
    """
    Compare original and parsed CSV data for round-trip consistency.
    
    Args:
        original: Original data before export
        parsed: Parsed data after import
        tolerance: Tolerance for floating point comparisons
    
    Returns:
        True if data matches within tolerance
    
    Raises:
        ValueError: If data doesn't match
    """
    # Compare headers
    if original.get('headers') != parsed.get('headers'):
        raise ValueError(
            f"Header mismatch: {original.get('headers')} != {parsed.get('headers')}"
        )
    
    # Compare row counts
    original_rows = original.get('rows', [])
    parsed_rows = parsed.get('rows', [])
    
    if len(original_rows) != len(parsed_rows):
        raise ValueError(
            f"Row count mismatch: {len(original_rows)} != {len(parsed_rows)}"
        )
    
    # Compare row data
    for idx, (orig_row, parsed_row) in enumerate(zip(original_rows, parsed_rows)):
        for key in orig_row.keys():
            orig_val = orig_row.get(key)
            parsed_val = parsed_row.get(key)
            
            # Handle None values
            if orig_val is None and parsed_val is None:
                continue
            
            if orig_val is None or parsed_val is None:
                raise ValueError(
                    f"Value mismatch in row {idx + 1}, column '{key}': "
                    f"{orig_val} != {parsed_val}"
                )
            
            # Handle numeric comparisons with tolerance
            if isinstance(orig_val, (int, float)) and isinstance(parsed_val, (int, float)):
                if abs(orig_val - parsed_val) > tolerance:
                    raise ValueError(
                        f"Numeric value mismatch in row {idx + 1}, column '{key}': "
                        f"{orig_val} != {parsed_val} (tolerance: {tolerance})"
                    )
            else:
                # Exact comparison for non-numeric values
                if str(orig_val) != str(parsed_val):
                    raise ValueError(
                        f"Value mismatch in row {idx + 1}, column '{key}': "
                        f"{orig_val} != {parsed_val}"
                    )
    
    logger.info("csv_comparison_passed", row_count=len(original_rows))
    
    return True
