# backend/app/utils/excel_parser.py

"""
Excel parser utility for round-trip testing.

This module provides functionality to parse Excel files generated by the
excel_generator utility and return structured data for validation.

Requirements: 28.1-28.3, 28.7
"""

from typing import Dict, List, Any, Optional
from pathlib import Path
import openpyxl
from openpyxl.worksheet.worksheet import Worksheet
from decimal import Decimal
from datetime import datetime, date

from app.logging_config import get_logger

logger = get_logger(__name__)


class ExcelParseError(Exception):
    """Exception raised when Excel parsing fails"""
    pass


def parse_excel(file_path: str) -> Dict[str, Any]:
    """
    Parse an Excel file and return structured data.
    
    This function reads an Excel workbook and extracts data from all worksheets,
    returning it in a structured format that matches the export format.
    
    Args:
        file_path: Path to the Excel file to parse
    
    Returns:
        Dictionary containing parsed data with worksheet names as keys
    
    Raises:
        ExcelParseError: If the file cannot be parsed or is invalid
        FileNotFoundError: If the file does not exist
    
    Example:
        >>> data = parse_excel('report.xlsx')
        >>> print(data.keys())
        dict_keys(['Financial Statement', 'Summary'])
    """
    file_path_obj = Path(file_path)
    
    if not file_path_obj.exists():
        raise FileNotFoundError(f"Excel file not found: {file_path}")
    
    try:
        workbook = openpyxl.load_workbook(file_path, data_only=True)
        
        result = {
            'metadata': _extract_metadata(workbook),
            'worksheets': {}
        }
        
        for sheet_name in workbook.sheetnames:
            worksheet = workbook[sheet_name]
            result['worksheets'][sheet_name] = _parse_worksheet(worksheet)
        
        workbook.close()
        
        logger.info(
            "excel_parsed",
            file_path=file_path,
            worksheet_count=len(result['worksheets'])
        )
        
        return result
        
    except Exception as e:
        logger.error(
            "excel_parse_failed",
            file_path=file_path,
            error=str(e)
        )
        raise ExcelParseError(f"Failed to parse Excel file: {str(e)}") from e


def _extract_metadata(workbook: openpyxl.Workbook) -> Dict[str, Any]:
    """
    Extract metadata from the workbook.
    
    Args:
        workbook: The openpyxl Workbook object
    
    Returns:
        Dictionary containing metadata
    """
    props = workbook.properties
    
    return {
        'title': props.title,
        'creator': props.creator,
        'created': props.created.isoformat() if props.created else None,
        'modified': props.modified.isoformat() if props.modified else None,
        'sheet_count': len(workbook.sheetnames),
        'sheet_names': workbook.sheetnames
    }


def _parse_worksheet(worksheet: Worksheet) -> Dict[str, Any]:
    """
    Parse a single worksheet and extract data.
    
    Args:
        worksheet: The openpyxl Worksheet object
    
    Returns:
        Dictionary containing worksheet data
    """
    # Get dimensions
    max_row = worksheet.max_row
    max_col = worksheet.max_column
    
    if max_row == 0 or max_col == 0:
        return {
            'headers': [],
            'rows': [],
            'row_count': 0,
            'column_count': 0
        }
    
    # Extract headers (first row)
    headers = []
    for col in range(1, max_col + 1):
        cell_value = worksheet.cell(row=1, column=col).value
        headers.append(str(cell_value) if cell_value is not None else '')
    
    # Extract data rows
    rows = []
    for row_idx in range(2, max_row + 1):
        row_data = {}
        for col_idx, header in enumerate(headers, start=1):
            if header:  # Only include columns with headers
                cell = worksheet.cell(row=row_idx, column=col_idx)
                row_data[header] = _parse_cell_value(cell)
        
        # Only add non-empty rows
        if any(v is not None and v != '' for v in row_data.values()):
            rows.append(row_data)
    
    return {
        'headers': headers,
        'rows': rows,
        'row_count': len(rows),
        'column_count': len(headers)
    }


def _parse_cell_value(cell) -> Any:
    """
    Parse a cell value and convert to appropriate Python type.
    
    Args:
        cell: The openpyxl Cell object
    
    Returns:
        Parsed value in appropriate Python type
    """
    value = cell.value
    
    if value is None:
        return None
    
    # Handle datetime objects
    if isinstance(value, datetime):
        return value.isoformat()
    
    if isinstance(value, date):
        return value.isoformat()
    
    # Handle numeric values
    if isinstance(value, (int, float)):
        # Check if it's a percentage (cell format contains %)
        if cell.number_format and '%' in cell.number_format:
            return float(value)
        return value
    
    # Handle boolean values
    if isinstance(value, bool):
        return value
    
    # Handle string values
    if isinstance(value, str):
        # Try to parse as number if it looks like one
        stripped = value.strip()
        
        # Check for currency symbols
        if stripped.startswith('$') or stripped.startswith('€'):
            try:
                return float(stripped.replace('$', '').replace('€', '').replace(',', ''))
            except ValueError:
                pass
        
        # Check for percentage
        if stripped.endswith('%'):
            try:
                return float(stripped.replace('%', '')) / 100
            except ValueError:
                pass
        
        return value
    
    return value


def validate_excel_data(data: Dict[str, Any], expected_structure: Optional[Dict[str, Any]] = None) -> bool:
    """
    Validate parsed Excel data against expected structure.
    
    Args:
        data: Parsed Excel data
        expected_structure: Optional expected structure to validate against
    
    Returns:
        True if validation passes
    
    Raises:
        ValueError: If validation fails
    """
    if 'worksheets' not in data:
        raise ValueError("Invalid Excel data: missing 'worksheets' key")
    
    if not isinstance(data['worksheets'], dict):
        raise ValueError("Invalid Excel data: 'worksheets' must be a dictionary")
    
    if expected_structure:
        expected_sheets = expected_structure.get('worksheets', {})
        
        for sheet_name, expected_sheet in expected_sheets.items():
            if sheet_name not in data['worksheets']:
                raise ValueError(f"Missing expected worksheet: {sheet_name}")
            
            actual_sheet = data['worksheets'][sheet_name]
            
            # Validate headers if specified
            if 'headers' in expected_sheet:
                expected_headers = expected_sheet['headers']
                actual_headers = actual_sheet['headers']
                
                if expected_headers != actual_headers:
                    raise ValueError(
                        f"Header mismatch in worksheet '{sheet_name}': "
                        f"expected {expected_headers}, got {actual_headers}"
                    )
    
    logger.info("excel_validation_passed", worksheet_count=len(data['worksheets']))
    
    return True
