"""Initial migration

Revision ID: 8383de60f631
Revises: 
Create Date: 2026-03-03 16:39:32.481031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8383de60f631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_items', sa.Column('quantity', sa.Float(), nullable=False))
    op.add_column('bom_items', sa.Column('unit', sa.String(length=50), nullable=True))
    op.add_column('bom_items', sa.Column('unit_cost', sa.Float(), nullable=False))
    op.add_column('bom_items', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('bom_items', 'quantity_per_unit')
    op.drop_column('bom_items', 'cost_per_component')
    op.drop_column('bom_items', 'supplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_items', sa.Column('supplier', sa.VARCHAR(length=255), nullable=True))
    op.add_column('bom_items', sa.Column('cost_per_component', sa.FLOAT(), nullable=False))
    op.add_column('bom_items', sa.Column('quantity_per_unit', sa.FLOAT(), nullable=False))
    op.drop_column('bom_items', 'notes')
    op.drop_column('bom_items', 'unit_cost')
    op.drop_column('bom_items', 'unit')
    op.drop_column('bom_items', 'quantity')
    # ### end Alembic commands ###
